version: '3.9'

services:

  db:
    image: pokemon-database:0.0.1
    restart: always
    shm_size: 128mb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pokemon
      POSTGRES_PASSWORD: pokemon
      POSTGRES_DB: pokemon
#    ports:
#      - 5434:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_started

  backend:
    image: pokemon-backend:0.0.1
    environment:
      DBNAME: pokemon
      PG_HOST: db
      PG_USER: pokemon
      PG_PASSWORD: pokemon
      PG_PORT: 5432
    ports:
      - 8000:80
    depends_on:
      db:
        condition: service_started
